version: "3.2"
services:
  server:
    container_name: "server"
    build: "./server/"
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - default
  db:
    image: postgres
    environment:
      POSTGRES_DB: chaos_dev
      POSTGRES_PASSWORD: chaos
      POSTGRES_USER: chaos
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
  smtp:
    image: mailhog/mailhog
    command: ["-smtp-bind-addr", "0.0.0.0:25"]
    user: root
    expose:
      - 25
      - 8025
    ports:
      - 8025:8025
    healthcheck:
      test: echo | telnet 127.0.0.1 25
    networks:
      - default

volumes:
  db-data:

networks:
  default:
